'use strict';
const $=id=>document.getElementById(id);
const ico=(name,cls='')=>`<svg class="icon ${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MISSIONS=[
 {name:'Primele litere',short:'Vocale',symbol:'A',chars:'AEIOU',note:'A E I O U · începem ușor',goal:15,theme:0},
 {name:'Acasă pe tastatură',short:'Acasă',symbol:'F J',chars:'ASDFJKL',note:'A S D F J K L · rândul de mijloc',goal:18,theme:0},
 {name:'Toate literele',short:'A–Z',symbol:'ABC',chars:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',note:'Întregul alfabet · o tastă pe rând',goal:20,theme:1},
 {name:'Planeta cifrelor',short:'Cifre',symbol:'123',chars:'0123456789',note:'0–9 · explorăm rândul de sus',goal:18,theme:2},
 {name:'Primele cuvinte',short:'Cuvinte',symbol:'Aa',chars:'ABCDEFGHIJKLMNOPQRSTUVWXYZ',words:['LUNA','MAMA','TATA','MERE','PERE','PISICA','CASA','APA','SOARE','NOR','MORCOV','URS','VULPE'],note:'Literele se unesc în cuvinte',goal:6,theme:0},
 {name:'Litere românești',short:'Ă Î Ș',symbol:'ĂȘ',chars:'ĂÂÎȘȚAEIOU',note:'Ă Â Î Ș Ț · taste suplimentare',goal:15,theme:1},
 {name:'Misiunea curcubeu',short:'Mix',symbol:'A7',chars:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',note:'Litere și cifre · toate împreună',goal:22,theme:2}
];
const STORAGE_KEY='luna-keyquest-v1';
const defaults=()=>({version:1,settings:{name:'',sound:true,music:false,hints:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,difficulty:'gentle',duration:75,lowercase:false},selected:0,mode:'adventure',seenTutorial:false,stars:0,totalHits:0,totalNumbers:0,totalWords:0,bestCombo:0,rounds:0,best:{},keys:{}});
let storageOK=true;
function load(){const d=defaults();try{const r=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(!r||r.version!==1)return d;Object.assign(d,r);d.settings=Object.assign(defaults().settings,r.settings||{});d.settings.name=String(d.settings.name||'').slice(0,20);d.selected=Number.isInteger(d.selected)?Math.max(0,Math.min(6,d.selected)):0;if(!['adventure','zen','duo'].includes(d.mode))d.mode='adventure';if(!['gentle','normal','fast'].includes(d.settings.difficulty))d.settings.difficulty='gentle';if(![75,120,180].includes(+d.settings.duration))d.settings.duration=75;for(const k of ['stars','totalHits','totalNumbers','totalWords','bestCombo','rounds'])d[k]=Math.max(0,Number(d[k])||0);if(typeof d.keys!=='object'||!d.keys)d.keys={};if(typeof d.best!=='object'||!d.best)d.best={};return d}catch(e){storageOK=false;return d}}
let data=load();
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));storageOK=true}catch(e){storageOK=false}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3200)}
const Audio={ctx:null,musicTimer:null,beat:0,unlock(){try{if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{})}catch(e){}},tone(f,d=.13,type='sine',vol=.09,delay=0){if(!data.settings.sound||!this.ctx)return;try{const c=this.ctx,o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+d+.04)}catch(e){}},hit(combo){const n=[523.25,587.33,659.25,783.99,880,1046.5][combo%6];this.tone(n,.14,'sine',.09);this.tone(n*2,.1,'sine',.025,.03)},miss(){this.tone(246.94,.1,'sine',.045)},win(){[523.25,659.25,783.99,1046.5].forEach((n,i)=>this.tone(n,.35,'sine',.09,i*.12))},startMusic(){this.stopMusic();if(!data.settings.music||!data.settings.sound)return;const notes=[261.63,329.63,392,329.63,220,329.63,440,392];this.musicTimer=setInterval(()=>{if(!document.hidden&&Game.running&&!Game.paused)this.tone(notes[this.beat++%notes.length],1.25,'sine',.018)},850)},stopMusic(){clearInterval(this.musicTimer);this.musicTimer=null}};
let modalClose=null,previousFocus=null,deferredInstall=null;
function showModal(content,onClose){previousFocus=document.activeElement;modalClose=onClose||(()=>{});$('modal').innerHTML=content;$('modal-backdrop').hidden=false;$('modal').focus();document.body.style.overflow='hidden'}
function closeModal(runCallback=true){const fn=modalClose;modalClose=null;$('modal-backdrop').hidden=true;$('modal').innerHTML='';document.body.style.overflow='';if(previousFocus&&previousFocus.isConnected)previousFocus.focus({preventScroll:true});if(runCallback&&fn)fn()}
const closeBtn=()=>`<button class="icon-btn modal-close" data-action="close-modal" aria-label="Închide">${ico('close')}</button>`;
function synchronize(){document.querySelectorAll('.fox-head').forEach(e=>e.innerHTML=HEAD_SVG);$('wallet-count').textContent=data.stars;document.body.classList.toggle('motion-reduced',!!data.settings.reduced);document.querySelectorAll('.sound-toggle').forEach(b=>{b.innerHTML=ico(data.settings.sound?'sound':'mute');b.setAttribute('aria-label',data.settings.sound?'Oprește sunetele':'Pornește sunetele');b.setAttribute('aria-pressed',String(!data.settings.sound))});$('welcome-label').textContent=data.settings.name?`Bun venit, ${data.settings.name}!`:'O mică misiune. O mare reușită.';document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===data.mode);b.setAttribute('aria-pressed',String(b.dataset.mode===data.mode))});const m=MISSIONS[data.selected];$('chosen-mission').textContent=m.name;$('mission-detail').textContent=m.note;$('start-button').querySelector('span').textContent=data.mode==='duo'?'Pornim împreună':data.mode==='zen'?'Hai să exersăm':'Începe aventura';const shown=[0,1,2,3,4];if(data.selected>4)shown[4]=data.selected;$('mission-rail').innerHTML=shown.map(i=>{const mm=MISSIONS[i],best=data.best[i]?.stars||0;return `<button class="mission-dot ${data.selected===i?'active ':''}${best?'done':''}" data-mission="${i}" aria-label="${mm.name}${best?', '+best+' stele':''}" aria-pressed="${data.selected===i}"><span class="orb"><span>${mm.symbol}</span>${best?'<span class="tiny-star">★</span>':''}</span><small>${mm.short}</small></button>`}).join('')+`<button class="mission-dot" data-action="missions" aria-label="Toate misiunile"><span class="orb"><span>＋</span></span><small>Mai multe</small></button>`;if(new URLSearchParams(location.search).has('native'))document.querySelectorAll('.install-link').forEach(b=>b.hidden=true)}
function setMode(mode){data.mode=mode;save();synchronize();Audio.unlock();Audio.tone(440,.09,'sine',.04)}
function selectMission(id){data.selected=Math.max(0,Math.min(MISSIONS.length-1,+id));save();synchronize();Audio.unlock();Audio.tone(523,.09,'sine',.04)}
function showMissions(){showModal(`${closeBtn()}<div class="eyebrow">Harta aventurii</div><h2 id="modal-title">Unde zburăm azi?</h2><p>Toate misiunile sunt deschise. Alege ce vrei să exersezi.</p><div class="mission-list">${MISSIONS.map((m,i)=>`<button class="mission-option ${data.selected===i?'active':''}" data-pick-mission="${i}"><span class="mission-symbol">${m.symbol}</span><span><b>${m.name}</b><small>${m.note}</small></span><span class="earned-stars">${'★'.repeat(data.best[i]?.stars||0)}</span></button>`).join('')}</div>`)}
function showHelp(begin=false){showModal(`${closeBtn()}<div class="eyebrow">Bună! Eu sunt Luna.</div><h2 id="modal-title">O tastă, o steluță!</h2><div class="help-step"><span class="step-key">A</span><div><b>Privește litera care coboară.</b><p>Fiecare bulă ascunde o literă sau o cifră.</p></div></div><div class="help-step"><span class="step-key" style="color:var(--mint)">${ico('keyboard')}</span><div><b>Găsește-o pe tastatură.</b><p>Apasă tasta de jos sau aceeași tastă pe tastatura reală. Nu trebuie să atingi bula.</p></div></div><div class="help-step"><span class="step-key" style="color:var(--gold)">${ico('star','fill')}</span><div><b>Pop! Ai adunat o steluță.</b><p>Luna te ajută dacă eziți. Nu pierzi vieți când greșești.</p></div></div><p class="callout">Pentru început: „Primele litere” + „Fără grabă”. Tastele verzi arată unde să apeși. Majusculele și literele mici funcționează la fel.</p><button class="primary" data-action="${begin?'tutorial-start':'close-modal'}">${ico('play','fill')}${begin?'Am înțeles. Să ne jucăm!':'Am înțeles!'}</button>`,()=>{if(begin)showHome()})}
function showSettings(){const s=data.settings;showModal(`${closeBtn()}<div class="eyebrow">Colțul părinților</div><h2 id="modal-title">Fiecare copil, ritmul lui.</h2><p>Un început blând și câteva minute de joacă împreună.</p><div class="setting"><label for="set-name">Prenume sau poreclă<small>Opțional. Rămâne doar pe acest dispozitiv.</small></label><input id="set-name" type="text" maxlength="20" autocomplete="off" value="${escapeHTML(s.name)}" placeholder="Explorator"></div><div class="setting"><label for="set-difficulty">Viteza literelor<small>Blând: mai mult timp și mai puține bule.</small></label><select id="set-difficulty"><option value="gentle" ${s.difficulty==='gentle'?'selected':''}>Blând · începător</option><option value="normal" ${s.difficulty==='normal'?'selected':''}>Vesel · intermediar</option><option value="fast" ${s.difficulty==='fast'?'selected':''}>Sprint · avansat</option></select></div><div class="setting"><label for="set-duration">Durata unei runde<small>În „Fără grabă” nu există cronometru.</small></label><select id="set-duration">${[75,120,180].map(d=>`<option value="${d}" ${+s.duration===d?'selected':''}>${d===75?'1 min 15 sec':d===120?'2 minute':'3 minute'}</option>`).join('')}</select></div><div class="setting"><label for="set-hints">Taste luminoase<small>Arată tasta pentru bula cea mai apropiată.</small></label><input id="set-hints" type="checkbox" ${s.hints?'checked':''}></div><div class="setting"><label for="set-lowercase">Litere mici<small>a, b, c în loc de A, B, C.</small></label><input id="set-lowercase" type="checkbox" ${s.lowercase?'checked':''}></div><div class="setting"><label for="set-music">Muzică discretă<small>O melodie liniștită, doar în timpul jocului.</small></label><input id="set-music" type="checkbox" ${s.music?'checked':''}></div><div class="setting"><label for="set-reduced">Mai puțină mișcare<small>Reduce plutirea, particulele și efectele.</small></label><input id="set-reduced" type="checkbox" ${s.reduced?'checked':''}></div><button class="primary" data-action="save-settings">Salvează și înapoi la joacă ${ico('arrow')}</button><div class="divider"></div><p class="micro">Nu există cont, reclame, cameră, microfon sau analiză de trafic în joc. Progresul rămâne în memoria locală a browserului/aplicației. Browserul și aplicația Android au salvări separate.</p><button class="text-btn" data-action="progress">${ico('trophy')}Vezi progresul și tastele exersate</button><button class="text-btn" data-action="reset-confirm" style="color:#b797b6">Resetează progresul de pe acest dispozitiv</button>`)}
function saveSettings(){data.settings={...data.settings,name:$('set-name').value.trim().slice(0,20),difficulty:$('set-difficulty').value,duration:Number($('set-duration').value),hints:$('set-hints').checked,lowercase:$('set-lowercase').checked,music:$('set-music').checked,reduced:$('set-reduced').checked};save();closeModal();synchronize();toast(storageOK?'Setările au fost salvate. Spor la joacă!':'Browserul nu permite salvarea locală. Setările se păstrează doar în această sesiune.')}
function showCollection(){const badges=[['star','Prima stea',data.stars>=1,'Adună prima stea.'],['keyboard','100 de taste',data.totalHits>=100,`${Math.min(100,data.totalHits)} / 100 taste corecte`],['rocket','Explorator',Object.values(data.best).filter(x=>x.stars>0).length>=3,'Câștigă stele în 3 misiuni.'],['sparkle','Pe val',data.bestCombo>=10,`${Math.min(10,data.bestCombo)} / 10 taste la rând`],['moon','Cifre istețe',data.totalNumbers>=30,`${Math.min(30,data.totalNumbers)} / 30 cifre corecte`],['trophy','Cuvinte magice',data.totalWords>=10,`${Math.min(10,data.totalWords)} / 10 cuvinte complete`]];showModal(`${closeBtn()}<div class="eyebrow">Micul tău univers</div><h2 id="modal-title">Colecția mea</h2><p>Fiecare reușită merită sărbătorită. Insignele se adună prin joacă.</p><div class="progress-summary"><div><b>${data.stars}</b><small>stele adunate</small></div><div><b>${data.totalHits}</b><small>taste găsite</small></div><div><b>${badges.filter(b=>b[2]).length}/6</b><small>insigne</small></div></div><div class="badge-grid">${badges.map(b=>`<div class="badge ${b[2]?'unlocked':''}"><div class="badge-icon">${ico(b[0],b[0]==='star'?'fill icon-xl':'icon-xl')}</div><b>${b[1]}</b><small>${b[2]?'Câștigată!':b[3]}</small></div>`).join('')}</div><button class="primary" data-action="close-modal">Înapoi la aventură ${ico('arrow')}</button>`)}
function showProgress(){showModal(`${closeBtn()}<div class="eyebrow">Progres local</div><h2 id="modal-title">Micile reușite contează.</h2><div class="progress-summary"><div><b>${data.rounds}</b><small>runde încheiate</small></div><div><b>${data.totalHits}</b><small>taste corecte</small></div><div><b>${data.bestCombo}</b><small>cea mai lungă serie</small></div></div><p>Verde: exersată. Auriu: merită puțină atenție în plus. Acesta este un jurnal de joacă, nu un test standardizat.</p><div class="key-heatmap">${'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ĂÂÎȘȚ'.split('').map(k=>{const v=data.keys[k];const needs=v&&v.miss>v.correct*.4;return `<span class="heat-key ${v?(needs?'needs-work':'practiced'):''}" title="${k}: ${v?.correct||0} corecte, ${v?.miss||0} de exersat">${k}</span>`}).join('')}</div><p class="callout">O tastatură fizică, conectată prin Bluetooth sau USB, folosește aceleași reguli. Începeți cu 5 litere, apoi adăugați treptat alte taste.</p><button class="secondary" data-action="settings">Înapoi la setări</button>`)}
function showInstall(){const installed=matchMedia('(display-mode: standalone)').matches||navigator.standalone;showModal(`${closeBtn()}<div class="eyebrow">Luna vine cu tine</div><h2 id="modal-title">Joacă pe tabletă.</h2><p>Jocul funcționează direct în browser, fără instalare. Pentru o pictogramă pe ecranul principal:</p>${installed?'<p class="callout">Jocul este deja deschis ca aplicație instalată.</p>':''}<div class="install-instructions"><div><b>Android · Chrome</b><br>Deschide meniul ⋮ al browserului, apoi „Adaugă pe ecranul de pornire” sau „Instalează aplicația”.</div><div><b>iPad · Safari</b><br>Apasă „Partajare”, apoi „Adăugați la ecranul principal”.</div><div><b>Joacă fără internet</b><br>Așteaptă mesajul „Gata pentru joacă offline” după prima deschidere online. Apoi redeschide jocul de pe același dispozitiv.</div></div>${deferredInstall?'<button class="primary" data-action="install-now">Instalează Luna KeyQuest</button>':''}<p class="micro">Aceasta este instalarea web (PWA). Un APK Android, când este disponibil, este un pachet separat. Ștergerea datelor browserului șterge și progresul.</p>`)}
function showHome(){Game.stop();closeModal(false);$('game-screen').hidden=true;$('home-screen').hidden=false;synchronize();requestAnimationFrame(initHomeArt);window.scrollTo({top:0,behavior:'instant'})}
let duoResults=[],duoRound=0;
function requestStart(){Audio.unlock();if(!data.seenTutorial){showHelp(true);return}beginSession()}
function beginSession(){closeModal(false);duoResults=[];duoRound=0;if(data.mode==='duo'){showHandoff()}else{startRound()}}
function showHandoff(){const first=duoRound===0;showModal(`<div class="result"><div class="eyebrow" style="justify-content:center">Împreună · runda ${duoRound+1} din 2</div><div style="color:var(--pink);margin:12px">${ico('duo','icon-xl')}</div><h2 id="modal-title">${first?'Începe micul explorator!':'Acum e rândul părintelui!'}</h2><p>${first?'Prima rundă este pentru copil. Părintele încurajează, fără să apese tastele.':'Dați tableta sau tastatura mai departe. Părintele primește aceeași misiune, dar cu bule puțin mai rapide.'}</p><p class="callout">Nu este o competiție. La final, punctele voastre se adună într-un scor de echipă.</p><button class="primary" data-action="duo-start">${ico('play','fill')}${first?'Sunt gata!':'Hai să facem echipă!'}</button><button class="secondary" data-action="go-home">Înapoi la meniu</button></div>`)}
function startRound(){closeModal(false);$('home-screen').hidden=true;$('game-screen').hidden=false;cancelAnimationFrame(homeRAF);homeRAF=0;window.scrollTo(0,0);requestAnimationFrame(()=>Game.start(MISSIONS[data.selected],data.mode,duoRound===1));}
const Game={running:false,paused:false,frame:0,items:[],particles:[],beams:[],popups:[],view:null,bg:null,mode:'adventure',m:null,last:0,elapsed:0,spawnClock:0,duration:75,score:0,hits:0,wrong:0,missed:0,cleared:0,combo:0,bestCombo:0,focusId:null,serial:0,freeze:0,coachUntil:0,keys:{},numHits:0,wordHits:0,seed:0,lastChar:'',isParent:false,
 start(m,mode,isParent=false){this.stop();this.m=m;this.mode=mode;this.isParent=isParent;this.running=true;this.paused=false;this.elapsed=0;this.spawnClock=0;this.score=0;this.hits=0;this.wrong=0;this.missed=0;this.cleared=0;this.combo=0;this.bestCombo=0;this.focusId=null;this.serial=0;this.freeze=0;this.coachUntil=0;this.keys={};this.numHits=0;this.wordHits=0;this.items=[];this.particles=[];this.beams=[];this.popups=[];this.lastChar='';this.duration=+data.settings.duration;this.seed=0;this.last=0;this.buildKeyboard();this.resize();$('game-mission').textContent=m.name;$('game-player').textContent=mode==='duo'?(isParent?'Runda 2 · Părintele':'Runda 1 · Micul explorator'):mode==='zen'?'Fără grabă · fără cronometru':(data.settings.name||'Luna e alături de tine');$('time-label').textContent=mode==='zen'?'Relax':'Timp';$('scene-message').innerHTML=`Adună <b>${m.goal} ${m.words?'cuvinte':'litere'+(data.selected===3?' / cifre':'')}</b> pentru 3 stele`;$('keyboard-hint-label').innerHTML=data.settings.hints?'Tasta verde te ajută · <span class="mini-key">ESC</span> pauză':'Tu găsești tastele · <span class="mini-key">ESC</span> pauză';this.say(m.words?'Scrie cuvântul, literă cu literă.':'Privește bula și găsește aceeași tastă.',5);this.spawn(true);this.hud();Audio.unlock();Audio.startMusic();this.frame=requestAnimationFrame(t=>this.tick(t));},
 stop(){this.running=false;this.paused=false;cancelAnimationFrame(this.frame);Audio.stopMusic();},
 resize(){if(!$('game-screen').hidden){const old=this.view;this.view=Graphics.setup($('game-canvas'));this.bg=Graphics.background(this.view.w,this.view.h,this.m?.theme||0);if(old&&old.w>0){this.items.forEach(it=>{it.x=it.x/old.w*this.view.w;it.y=Math.min(it.y/old.h*this.view.h,this.view.h*.8);it.r=this.radius(it.text)})}this.draw(performance.now()/1000)}},
 radius(text){const v=this.view;const base=Math.min(37,Math.max(25,v.w*.062),Math.max(23,v.h*.105));return text.length>1?Math.min(base+text.length*5.4,v.w*.29):base;},
 speed(){const factors={gentle:1,normal:1.4,fast:1.9};return factors[data.settings.difficulty]*(this.isParent?1.3:1);},
 buildKeyboard(){const rows=['1234567890','QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];if(this.m.chars.includes('Ș'))rows.push('ĂÂÎȘȚ');$('keyboard').innerHTML=rows.map((r,i)=>`<div class="key-row" data-row="${i}">${r.split('').map(k=>`<button class="key ${data.settings.lowercase?'lower':''}" data-key="${k}" aria-label="Tasta ${k}" tabindex="0">${k}</button>`).join('')}</div>`).join('')},
 target(){if(this.focusId){const t=this.items.find(i=>i.id===this.focusId);if(t)return t;this.focusId=null}return this.items.reduce((a,b)=>!a||b.y>a.y?b:a,null)},
 choose(){const pool=this.m.words||this.m.chars.split('');if(this.seed++===0)return pool[0];const weighted=[];pool.forEach(k=>{weighted.push(k);const hist=data.keys[k];if(!this.m.words&&hist&&hist.miss>hist.correct*.3)weighted.push(k,k)});const choices=weighted.filter(k=>k!==this.lastChar);return (choices.length?choices:weighted)[Math.floor(Math.random()*(choices.length||weighted.length))]},
 spawn(first=false){if(!this.view)return;const text=this.choose();this.lastChar=text;const {w,h}=this.view,r=this.radius(text);let x=w*.5;const margin=r+18;if(!first){let best=-1;for(let i=0;i<12;i++){const xx=margin+Math.random()*Math.max(0,w-margin*2);const dist=this.items.reduce((n,t)=>Math.min(n,Math.abs(t.x-xx)),w);if(dist>best){best=dist;x=xx}}}this.items.push({id:++this.serial,text,done:0,x,y:first?Math.max(r+58,h*.19):r+54,r,age:0,born:this.elapsed,color:PALETTE[(text.charCodeAt(0)+this.serial)%PALETTE.length],phase:Math.random()*6});this.updateHints()},
 updateHints(){const target=this.target(),key=target?target.text[target.done]:null;document.querySelectorAll('.key').forEach(b=>{const k=b.dataset.key;b.classList.toggle('hint',!!(data.settings.hints&&key===k));b.classList.toggle('relevant',this.items.some(it=>it.text[it.done]===k))})},
 say(text,secs=3){if($('coach').textContent!==text)$('coach').textContent=text;this.coachUntil=this.elapsed+secs;},
 tick(ts){if(!this.running)return;const dt=this.last?Math.min((ts-this.last)/1000,.05):0;this.last=ts;if(!this.paused){this.elapsed+=dt;const capped=window.matchMedia('(prefers-reduced-motion: reduce)').matches||data.settings.reduced;const zen=this.mode==='zen';this.freeze=Math.max(0,this.freeze-dt);this.spawnClock+=dt;let interval=(this.m.words?7.5:4.1)/this.speed();let cap=zen?1:this.m.words?2:data.settings.difficulty==='gentle'?3:5;if(this.elapsed<6)cap=1;if(this.items.length<cap&&this.spawnClock>interval){this.spawn();this.spawnClock=0}const {h}=this.view;let speed=Math.max(9,(h-75)/19)*this.speed()*(this.freeze>0?.33:1);for(let i=this.items.length-1;i>=0;i--){const it=this.items[i];it.age+=dt;if(zen){const yy=Math.max(it.r+62,h*.40);it.y+=Math.max(0,Math.min(yy-it.y,dt*speed));}else{it.y+=speed*dt;if(it.y>h-it.r*.65-40){this.missed++;this.combo=0;this.freeze=2.5;const k=it.text[it.done];this.record(k,false);this.burst(it.x,Math.min(it.y,h-40),it.color,8);this.items.splice(i,1);if(this.focusId===it.id)this.focusId=null;this.say('Nu-i nimic. Vine o nouă șansă!',3.5);this.updateHints();this.hud()}}}
 this.particles=this.particles.filter(p=>p.life>0);this.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=55*dt});this.beams=this.beams.filter(b=>b.life>0);this.beams.forEach(b=>b.life-=dt);this.popups=this.popups.filter(p=>p.life>0);this.popups.forEach(p=>{p.life-=dt;p.y-=dt*25});if(this.elapsed>this.coachUntil){const target=this.target();if(target&&target.age>3&&data.settings.hints){const kk=target.text[target.done];this.say(`Găsește tasta ${data.settings.lowercase?kk.toLowerCase():kk}. Luna îți arată unde.`,3)}else if(zen){this.say('Avem tot timpul din lume. O tastă pe rând.',6)}else{this.say('Fiecare tastă potrivită aprinde o stea.',5)}}
 this.hud();if(!zen&&this.elapsed>=this.duration){this.finish();return}if(zen&&this.cleared>=this.m.goal){this.finish();return}}
 this.draw(ts/1000);this.frame=requestAnimationFrame(t=>this.tick(t))},
 record(k,correct){if(!this.keys[k])this.keys[k]={correct:0,miss:0};this.keys[k][correct?'correct':'miss']++},
 press(raw){if(!this.running||this.paused||!$('modal-backdrop').hidden)return;const key=raw.toLocaleUpperCase('ro').replace('Ş','Ș').replace('Ţ','Ț');if(!/^[A-Z0-9ĂÂÎȘȚ]$/.test(key))return;Audio.unlock();const target=this.target();if(!target)return;let item;if(this.focusId){item=target.text[target.done]===key?target:null}else{item=this.items.filter(it=>it.text[it.done]===key).sort((a,b)=>b.y-a.y)[0]}
 const button=$('keyboard').querySelector(`[data-key="${key}"]`);if(button){button.classList.add(item?'pressed':'oops');setTimeout(()=>button.classList.remove('pressed','oops'),150)}
 if(!item){this.wrong++;this.combo=0;this.record(target.text[target.done],false);Audio.miss();this.say(`Încearcă tasta ${data.settings.lowercase?target.text[target.done].toLowerCase():target.text[target.done]}. Ești pe drumul bun!`,3);this.hud();return}
 this.hits++;this.combo++;this.bestCombo=Math.max(this.bestCombo,this.combo);this.record(key,true);if(/\d/.test(key))this.numHits++;const multiplier=Math.min(4,1+Math.floor(this.combo/5));const points=10*multiplier;this.score+=points;item.done++;this.focusId=item.id;this.beams.push({x:item.x,y:item.y,life:.22,max:.22,color:item.color});this.popups.push({x:item.x,y:item.y-item.r,life:.7,text:'+'+points,color:item.color});Audio.hit(this.combo);if(item.done>=item.text.length){this.cleared++;if(this.m.words){this.wordHits++;this.score+=30;this.say(`Bravo! Ai scris ${item.text}!`,3)}this.burst(item.x,item.y,item.color,data.settings.reduced?5:24);this.items=this.items.filter(t=>t!==item);this.focusId=null;this.spawnClock=Math.max(this.spawnClock,2.5);if(this.combo%5===0)this.say(['Super! Tastele prind viață!','Uau! Luna e mândră de tine!','Strălucești, mic explorator!'][Math.floor(this.combo/5)%3],3);if(this.items.length===0){this.spawnClock=0;this.spawn()}}this.updateHints();this.hud();},
 burst(x,y,color,count){for(let i=0;i<count&&this.particles.length<180;i++){const a=Math.random()*Math.PI*2,v=25+Math.random()*110;this.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-30,life:.45+Math.random()*.55,max:1,r:2+Math.random()*4,color,star:i%3===0})}},
 stars(){return this.cleared>=this.m.goal?3:this.cleared>=Math.ceil(this.m.goal*2/3)?2:this.cleared>=Math.ceil(this.m.goal/3)?1:0},
 hud(){const score=String(this.score);if($('score').textContent!==score)$('score').textContent=score;const sec=Math.max(0,Math.ceil(this.duration-this.elapsed));const tt=this.mode==='zen'?'∞':`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if($('time').textContent!==tt)$('time').textContent=tt;const st=this.stars();$('game-stars').querySelectorAll('svg').forEach((e,i)=>e.classList.toggle('earned',i<st));$('star-progress').style.width=Math.min(100,this.cleared/this.m.goal*100)+'%';const multi=Math.min(4,1+Math.floor(this.combo/5));$('combo-chip').classList.toggle('visible',this.combo>=5);$('combo-chip').textContent=`${this.combo} LA RÂND · ×${multi}`;},
 draw(t){const v=this.view;if(!v||v.w===0||v.h===0)return;const {c,w,h}=v;const reduced=data.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;if(this.bg)c.drawImage(this.bg,0,0,w,h);else{c.fillStyle='#211933';c.fillRect(0,0,w,h)}const tm=reduced?0:t;for(let i=0;i<11;i++){c.globalAlpha=.18+Math.sin(tm*.8+i)*.12;c.fillStyle=i%2?'#d6caff':'#acdfc8';starPath(c,(i*137+27)%w,((i*89+67)%(h*.8)),i%3===0?5:3);c.fill()}c.globalAlpha=1;const shipScale=Math.min(.65,Math.max(.38,w/1400),h/260);const sx=w*.5,sy=h-38;Graphics.ship(c,sx,sy,shipScale,tm);if(headImage.complete){const fs=shipScale*50;c.drawImage(headImage,sx-fs*.5,sy-fs*.9,fs,fs)}c.save();c.strokeStyle='#b396d524';c.setLineDash([3,7]);c.beginPath();c.moveTo(15,h-58);c.lineTo(w-15,h-58);c.stroke();c.restore();
 this.beams.forEach(b=>{const a=Math.max(0,b.life/b.max);c.save();c.strokeStyle=b.color;c.globalAlpha=a;c.shadowBlur=20;c.shadowColor=b.color;c.lineWidth=2+3*a;c.beginPath();c.moveTo(sx,sy);c.quadraticCurveTo((sx+b.x)/2,sy-65,b.x,b.y);c.stroke();c.restore()});
 for(const it of this.items){const x=it.x+(reduced?0:Math.sin(tm*1.6+it.phase)*3.5),y=it.y;const isFocus=it.id===this.focusId;if(isFocus&&it.text.length>1){c.save();c.strokeStyle='#a1f6d550';c.lineWidth=1;c.setLineDash([4,5]);c.beginPath();c.arc(x,y,it.r+6,0,Math.PI*2);c.stroke();c.restore()}const disp=data.settings.lowercase?it.text.toLocaleLowerCase('ro'):it.text;bubble(c,x,y,it.r,disp,it.color,tm,it.done);if(it.text.length>1&&it.done===0){c.fillStyle='#d8cae980';c.font='9px Trebuchet MS,sans-serif';c.textAlign='center';c.fillText('SCRIE CUVÂNTUL',x,y+it.r+14)}}
 for(const p of this.particles){c.save();c.globalAlpha=Math.min(1,p.life*1.8);c.fillStyle=p.color;if(p.star){starPath(c,p.x,p.y,p.r*1.4,5);c.fill()}else{c.beginPath();c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill()}c.restore()}for(const p of this.popups){c.save();c.globalAlpha=Math.min(1,p.life*2);c.font='900 20px Trebuchet MS,sans-serif';c.textAlign='center';c.fillStyle=p.color;c.shadowColor='#201431';c.shadowBlur=8;c.fillText(p.text,p.x,p.y);c.restore()}},
 pause(){if(!this.running||this.paused)return;this.paused=true;Audio.stopMusic();showModal(`${closeBtn()}<div class="result"><div style="color:var(--violet);margin:5px 0 14px">${ico('moon','icon-xl')}</div><h2 id="modal-title">O mică pauză.</h2><p>Stelele te așteaptă. Jocul și cronometrul sunt oprite.</p><button class="primary" data-action="resume">${ico('play','fill')}Continuă aventura</button><button class="secondary" data-action="finish-early">Încheie runda și salvează</button><button class="secondary" data-action="go-home">Înapoi la meniu, fără a salva runda</button><button class="text-btn" data-action="fullscreen" style="margin:12px auto 0">${ico('fullscreen')}Ecran complet</button></div>`,()=>this.resume())},
 resume(){if(!this.running)return;closeModal(false);this.paused=false;this.last=0;Audio.unlock();Audio.startMusic();},
 finish(){if(!this.running)return;this.stop();closeModal(false);const stars=this.stars();const attempts=this.hits+this.wrong;const accuracy=attempts?Math.round(this.hits/attempts*100):0;const missed=this.missed;const key=`${data.selected}`;const prior=data.best[key]||{score:0,stars:0};const record=this.score>prior.score;data.best[key]={score:Math.max(prior.score,this.score),stars:Math.max(prior.stars,stars)};data.stars+=stars;data.totalHits+=this.hits;data.totalNumbers+=this.numHits;data.totalWords+=this.wordHits;data.bestCombo=Math.max(data.bestCombo,this.bestCombo);data.rounds++;for(const [k,v]of Object.entries(this.keys)){if(!data.keys[k])data.keys[k]={correct:0,miss:0};data.keys[k].correct+=v.correct;data.keys[k].miss+=v.miss}save();synchronize();Audio.win();const result={score:this.score,stars,hits:this.hits,accuracy,missed};if(this.mode==='duo'){duoResults.push(result);if(duoRound===0){duoRound=1;showModal(`<div class="result"><div class="result-fox">${FOX_SVG}</div><h2 id="modal-title">Bravo, mic explorator!</h2><p>Ai găsit ${this.hits} taste și ai adunat ${this.score} puncte pentru echipă.</p><div class="result-stars">${[0,1,2].map(i=>`<span class="${i<stars?'on':''}">★</span>`).join('')}</div><p>Acum dați tastatura mai departe.</p><button class="primary" data-action="duo-handoff">Rândul părintelui ${ico('arrow')}</button><button class="secondary" data-action="go-home">Încheiem aici</button></div>`,showHome);return}showModal(`<div class="result"><div class="result-fox">${FOX_SVG}</div><div class="eyebrow" style="justify-content:center">Misiune de echipă</div><h2 id="modal-title">Împreună străluciți!</h2><p>Două runde, o aventură minunată.</p><div class="duo-score"><div><strong>Micul explorator</strong><b>${duoResults[0].score}</b></div><div><strong>Părintele</strong><b>${duoResults[1].score}</b></div></div><div class="best-badge">${duoResults.reduce((s,r)=>s+r.score,0)} puncte împreună · ${duoResults.reduce((s,r)=>s+r.stars,0)} stele</div><p class="micro">Ritmul părintelui este mai rapid. Scorurile sunt pentru echipă, nu pentru comparație.</p><button class="primary" data-action="replay">Încă o aventură împreună</button><button class="secondary" data-action="go-home">Înapoi la hartă</button></div>`,showHome);return}
 showModal(`<div class="result"><div class="result-fox">${FOX_SVG}</div><h2 id="modal-title">${stars===3?'Ai aprins toate stelele!':stars>0?'Uite cât de bine te descurci!':'Fiecare încercare contează!'}</h2><p>${stars===3?'Luna îți trimite o îmbrățișare cosmică.':stars>0?'O tastă pe rând, prinzi tot mai multă încredere.':'Luna e alături de tine. Putem exersa mai încet, fără cronometru.'}</p><div class="result-stars">${[0,1,2].map(i=>`<span class="${i<stars?'on':''}">★</span>`).join('')}</div>${record?'<span class="best-badge">Un nou record pentru această misiune!</span>':''}<div class="result-stats"><div><b>${this.score}</b><small>PUNCTE</small></div><div><b>${this.hits}</b><small>TASTE CORECTE</small></div><div><b>${accuracy}%</b><small>PRECIZIA TASTELOR</small></div></div><p class="micro">${this.cleared} ${this.m.words?'cuvinte':'bule'} prinse · ${missed} bule trecute · ${this.wrong} taste de reîncercat.<br>Precizia = taste corecte / toate tastele apăsate.</p>${!storageOK?'<p class="callout">Progresul nu a putut fi salvat în acest browser.</p>':''}<button class="primary" data-action="${stars===3?'next-mission':'replay'}">${ico('play','fill')}${stars===3?'Următoarea misiune':'Mai jucăm o dată'}</button>${stars===0&&this.mode!=='zen'?'<button class="secondary" data-action="try-zen">Încercăm „Fără grabă”</button>':''}<button class="secondary" data-action="go-home">Înapoi la hartă</button></div>`,showHome)}
};
const actions={
 'close-modal':()=>closeModal(),'help':()=>showHelp(),'settings':showSettings,'save-settings':saveSettings,'missions':showMissions,'collection':showCollection,'progress':showProgress,'install':showInstall,
 'tutorial-start':()=>{data.seenTutorial=true;save();beginSession()},'duo-start':startRound,'duo-handoff':showHandoff,'resume':()=>Game.resume(),'go-home':showHome,'replay':beginSession,'next-mission':()=>{selectMission((data.selected+1)%MISSIONS.length);beginSession()},'try-zen':()=>{setMode('zen');beginSession()},'finish-early':()=>Game.finish(),
 'fullscreen':async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){toast('Poți deschide jocul pe tot ecranul după instalare.')}},
 'install-now':async()=>{if(deferredInstall){await deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;closeModal()}},
 'reset-confirm':()=>showModal(`${closeBtn()}<h2 id="modal-title">Resetezi progresul?</h2><p>Se șterg stelele, recordurile și tastele exersate de pe acest dispozitiv. Această acțiune nu poate fi anulată.</p><div class="setting"><label for="reset-word">Scrie RESET</label><input id="reset-word" type="text" autocomplete="off" maxlength="5"></div><button class="secondary" data-action="reset-now">Șterge progresul local</button><button class="primary" data-action="settings">Păstrează progresul</button>`),
 'reset-now':()=>{if($('reset-word').value!=='RESET'){toast('Scrie RESET pentru a confirma.');return}data=defaults();save();closeModal();synchronize();toast('Un nou început. Luna te așteaptă!')}
};
document.addEventListener('click',e=>{const mode=e.target.closest('[data-mode]');if(mode){setMode(mode.dataset.mode);return}const mission=e.target.closest('[data-mission]');if(mission){selectMission(mission.dataset.mission);return}const pick=e.target.closest('[data-pick-mission]');if(pick){selectMission(pick.dataset.pickMission);closeModal();return}const a=e.target.closest('[data-action]');if(a){Audio.unlock();actions[a.dataset.action]?.();return}if(e.target.closest('.sound-toggle')){data.settings.sound=!data.settings.sound;Audio.unlock();save();synchronize();if(data.settings.sound)Audio.startMusic();else Audio.stopMusic();return}if(e.target.closest('.key')&&e.detail===0){Game.press(e.target.closest('.key').dataset.key)}});
$('keyboard').addEventListener('pointerdown',e=>{const b=e.target.closest('.key');if(!b)return;e.preventDefault();Game.press(b.dataset.key)});
$('start-button').addEventListener('click',requestStart);$('pause-button').addEventListener('click',()=>Game.pause());$('brand-home').addEventListener('click',()=>{});
$('game-canvas').addEventListener('pointerdown',e=>{if(!Game.running||Game.paused)return;const target=Game.target();if(target)Game.say(`Apasă tasta ${target.text[target.done]} de pe tastatura de jos.`,4)});
$('modal-backdrop').addEventListener('click',e=>{if(e.target===$('modal-backdrop')&&modalClose)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Tab'&&!$('modal-backdrop').hidden){const nodes=$('modal').querySelectorAll('button:not([disabled]),input,select,[tabindex="0"]');const first=nodes[0],last=nodes[nodes.length-1];if(!nodes.length){e.preventDefault();return}if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('modal'))){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}return}const target=e.target;if(target.matches('input,select,textarea'))return;if(e.key==='Escape'){e.preventDefault();if(!$('modal-backdrop').hidden){closeModal();return}if(Game.running)Game.pause();return}if(Game.running&&!Game.paused&&$('modal-backdrop').hidden&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&e.key.length===1){if(e.repeat)return;e.preventDefault();Game.press(e.key)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(Game.running&&!Game.paused)Game.pause();Audio.stopMusic();cancelAnimationFrame(homeRAF);homeRAF=0}else if(!$('home-screen').hidden)initHomeArt()});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!$('home-screen').hidden)initHomeArt();else Game.resize()},80)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
window.addEventListener('appinstalled',()=>{deferredInstall=null;toast('Luna are acum o casă pe ecranul tău!')});
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol)&&!new URLSearchParams(location.search).has('native')){window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{if(!sessionStorage.getItem('luna-offline-ready')){sessionStorage.setItem('luna-offline-ready','1');toast('Gata pentru joacă offline. Luna vine cu tine!')}}).catch(()=>{})})}
window.LunaApp={pause:()=>Game.pause(),home:showHome,handleBack:()=>{if(!$('modal-backdrop').hidden){closeModal();return true}if(Game.running){Game.pause();return true}return false}};
synchronize();requestAnimationFrame(initHomeArt);
