'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),E=require('./engine.js'),P=require('./persistence.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
test('48 unique connected grid shapes',()=>{const set=new Set;for(const shape of E.SHAPES){const seen=new Set([shape[0].join(',')]);let old=0;while(seen.size!==old){old=seen.size;for(const [x,y]of shape)if([[x-1,y],[x+1,y],[x,y-1],[x,y+1]].some(c=>seen.has(c.join(','))))seen.add([x,y].join(','));}assert.equal(seen.size,shape.length);set.add(shape.map(c=>c.join(',')).sort().join(';'));assert.deepEqual(E.rotated(shape,4),shape)}assert.equal(set.size,48)});
test('24 strictly rising Adventure line goals and tightening move ratios',()=>{for(let n=2;n<=24;n++){const a=E.levelSpec(n-1),b=E.levelSpec(n);assert.ok(b.target>a.target);assert.ok(b.moves/b.target<a.moves/a.target);assert.ok(b.shapeCount>=a.shapeCount);assert.ok(b.helpers<=a.helpers)}});
test('every Adventure level has a replayed winning solution',()=>{const paths=JSON.parse(fs.readFileSync(__dirname+'/solutions.json'));assert.equal(Object.keys(paths).length,24);for(let n=1;n<=24;n++){const s=E.newGame('adventure',n);for(const [act,...a]of paths[n]){assert.ok(E[act](s,...a).ok);assert.ok(E.validate(s));}assert.equal(s.status,'won');assert.ok(s.lines>=s.target&&s.gems>=s.gemTarget&&s.bestCombo>=s.comboTarget)}});
test('late Adventure missions require more than the line count',()=>{const s=E.newGame('adventure',20);s.lines=s.target;s.gems=0;s.bestCombo=0;E.place(s,0,3,7);assert.notEqual(s.status,'won')});
test('Prism ends after precisely 40 placements',()=>{const s=E.newGame('prism',1,17);s.moves=39;s.board.fill(0);s.tray[0]={cells:[[0,0]],color:1,uid:999};assert.ok(E.place(s,0,0,0).ok);assert.equal(s.status,'won');assert.equal(s.moves,40);assert.equal(E.place(s,1,3,3).ok,false)});
test('Prism rotations are free, reversible and do not change score',()=>{const s=E.newGame('prism',1,42),original=E.copy(s.tray[0]);for(let t=0;t<4;t++)assert.ok(E.rotate(s,0).ok);assert.deepEqual(s.tray[0],original);assert.equal(s.moves,0);assert.equal(s.score,0);assert.equal(E.rotate(E.newGame('classic'),0).ok,false)});
test('Prism scoring multiplier grows at five-line milestones',()=>{const a=E.newGame('prism'),b=E.newGame('prism');for(const s of [a,b]){s.board.fill(0);s.tray[0]={cells:[[0,0]],color:1,uid:500}}b.lines=10;const x=E.place(a,0,0,0),y=E.place(b,0,0,0);assert.equal(y.earned,x.earned*3)});
test('2000 legal Cozy moves preserve serializable valid state',()=>{const s=E.newGame('cozy',1,42);for(let i=0;i<2000;i++){const h=E.hint(s);assert.ok(h);assert.ok(E.place(s,h.slot,h.x,h.y).ok);assert.ok(E.validate(s));}assert.equal(E.restore(E.serialize(s)).moves,2000)});
test('50,000 best never drops after lower run or Undo',()=>{let p=P.record({}, {mode:'cozy',score:50000});p=P.record(p,{mode:'cozy',score:100});assert.equal(p.bests.cozy,50000);p=P.record(p,{mode:'cozy',score:51000});assert.equal(p.bests.cozy,51000)});
test('native snapshot wins over cleared browser storage and merges higher scores',()=>{let disk='{}',writes=0;const local={getItem(){return null},setItem(){},removeItem(){}},native={read(){return disk},write(s){disk=s;writes++;return true}};let a=P.create(local,native);a.set('bloom.profile',JSON.stringify({bests:{cozy:50000}}));assert.ok(a.flush());a=P.create(local,native);assert.equal(JSON.parse(a.get('bloom.profile')).bests.cozy,50000);a.set('bloom.profile',JSON.stringify({bests:{cozy:3,prism:99}}));assert.ok(a.flush());assert.equal(JSON.parse(a.get('bloom.profile')).bests.cozy,50000);assert.equal(writes,2)});
test('failed native writes are reported and retried',()=>{let tries=0;const a=P.create({getItem(){return null},setItem(){}},{read(){return '{}'},write(){return ++tries>1}});assert.equal(a.flush(),false);assert.equal(a.flush(),true);assert.equal(tries,2)});
test('malformed profile, negative scores and impossible state are rejected safely',()=>{assert.equal(P.normalizeProfile(null).bests.cozy,0);assert.equal(P.normalizeProfile({bests:{cozy:-55}}).bests.cozy,0);assert.equal(E.restore('{bad'),null);const s=E.newGame('prism');s.moveLimit=0;assert.equal(E.validate(s),false)});
console.log('ALL '+count+' ENGINE / PERSISTENCE TEST GROUPS PASSED');
